# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Configure the English version of the site.

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

nl:
  languageCode: nl-nl
  contentDir: content/nl
  title: "Rozemarijn van Dijk"
