# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Configure the English version of the site.

[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

[nl]
  languageCode = "nl-nl"
  contentDir = "content/nl"
  title = "Rozemarijn van Dijk"
  [nl.params]
    description = "Rozemarijn van Dijk, politicoloog Universiteit Antwerpen"
